### ISSUE TITLE
Data Persistence and Clean Architecture

### ISSUE THREAD

**Issue by lanthony42** [CSC207-UofT/course-project-aarves#43]
Here are some of my thoughts regarding the current state of our data persistence system, and some Clean Architecture related issues. 
First, here is an approximate diagram for the current implementation. Note that I put `ReviewList` in the use cases layer, since apparently `Map`s are use cases.

![current_database_system](https://user-images.githubusercontent.com/7217219/141151775-6fcf5933-31d3-47a8-ba12-a05dfdfe5a2a.png)

One apparent problem would be that the `ReviewSerializer` must be on the lowest level since it directly uses `GSON` to store data, which presents a problem since it depends on a use case. This might not necessarily be an issue because in reality Clean Architecture is never mentioned to be a strict layered architecture, though the course slides say so (so which should we follow?). The more pressing issue is that, according to the book:

> The important thing is that isolated, simple data structures are passed across the boundaries. We don’t want to cheat and pass Entity objects or database rows.

What we are doing is basically passing a use case which contains entities across boundaries which is probably an even more severe form of 'cheating'. However, many data persistence frameworks do this, where entities are directly referred to for persistence purposes, at least for the newer frameworks I think. Even in the following picture from the book:

![image](https://user-images.githubusercontent.com/7217219/141158905-ecc96bc0-9d63-4404-8436-e0a286316837.png)

The `DataAccessInterface` depends on entities, which means its concretion in the outermost layer would probably need to as well? Some ideas are as follows:

**Comment by lanthony42** [comment]
My thought would be to use a slightly less common implementation of a Repository pattern. Usually a Repository pattern would have an interface and a concretion, and it makes sense for (at the very least the interface) to be on the use cases layer since it is a higher level abstraction which should deal with entities. However because of Clean Architecture, the concretion would have to be on the same layer as the interface (in my interpretation), since it would also have to refer to entities. So instead, we would use the Data Access Object to act as the mediator between the data and the application (which would be used instead for testing), with the Repository transforming the entities into Data Transfer Objects to conform with Clean Architecture. This seems like a lot of boilerplate code and possibly repeated code, but it does conform with Clean Architecture.

**Comment by lanthony42** [comment]
Something like this:

![repository_database_system](https://user-images.githubusercontent.com/7217219/141167170-9ed68267-3fb9-4e3d-8258-00014cdc5540.png)

Yes, it skips the interface adapter layer, but so does Uncle Bob's example, and Uncle Bob is the law. We can justify this by saying doing anything else would be middle-manning (code smell!). So in reality, this system is basically the example except we added some things to conform better to Uncle Bob's own words. 

Or so I hope.

**Comment by rebplane** [comment]
From what I'm understanding, ReviewRepository would act somewhat list ReviewList right now. 

I'm not really understanding ReviewDTO. More specifically:

What is the difference between ReviewDTO and ReviewList? It seems like they both just hold data in the same way? 

Or would DTO be responsible for grabbing the data to/from ReviewRepository and sending it to GSONDataAccess, and the opposite for loading back into ReviewRepository? Would considering ReviewRepository to be an entity break anything dependency wise? Else, we can consider it a use case I guess. If that's the case, we can consider it a use case (maybe)?

**Comment by lanthony42** [comment]
`ReviewRepository` is a use case (see picture above). The `ReviewDTO` is created by `ReviewRepository` in order for it to interact with `DataAccess`, and it stores data corresponding to a `Review`. And yea, `GSONDataAccess` would also create `ReviewDTO`s to return to `ReviewRepository`.

**Comment by luwnehctik** [comment]
Would ReviewRepository replace ReviewList (would ReviewList become obsolete?)

Or is it a use case for ReviewList's review map?

**Comment by rebplane** [comment]
Would ReviewRepository then replace ReviewList (would ReviewList then become obsolete)? 

Or, would ReviewRepository be a use case for ReviewList's review map?

**Comment by lanthony42** [comment]
I would think this makes `ReviewList` obsolete. I'm investigating a possible implementation using a Strategy pattern with a Decorator pattern (which I think you did?). The ideas are [here](https://stackoverflow.com/questions/102913/caching-data-objects-when-using-repository-service-pattern-and-mvc).

**Comment by lanthony42** [comment]
The fix will be done in #58.
